spring:
  datasource:
    url: jdbc:postgresql://db:5432/account_service
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/dev-local
    schemas: account_schema
    default-schema: account_schema

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: account_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

