spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration
    schemas: image_schema
    default-schema: image_schema

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: image_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

minio:
  endpoint: http://marche-conclu-minio.web.1:9000
  public-url: https://marche-conclu-minio.cluster-ig5.igpolytech.fr:9000
  bucket-name: marche-conclu-images-dev
  region: us-east-1

