spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://marche-conclu-keycloak.web:8080/realms/marche-conclu

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1

            - id: shop-service
              uri: lb://shop-service
              predicates:
                - Path=/shop/**
              filters:
                - StripPrefix=1

            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
      
            - id: order-service
              uri: lb://order-service 
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1

            - id: image-service
              uri: lb://image-service
              predicates:
                - Path=/image/**
              filters:
                - StripPrefix=1

app:
  security:
    public-paths:
      - /public/**
      - /health
      - /actuator/info
