spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:3000/realms/marche-conclu

app:
  security:
    public-paths:
      - /public/**
      - /health
      - /actuator/info
