spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://marche-conclu-keycloak.cluster-ig5.igpolytech.fr/realms/marche-conclu
          jwk-set-uri: http://marche-conclu-keycloak.web:8080/realms/marche-conclu/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1   # removes "notification" before forwarding
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
            - id: shop-service
              uri: lb://shop-service
              predicates:
                - Path=/shop/**
              filters:
                - StripPrefix=1
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1

app:
  security:
    public-paths:
      - /public/**
      - /health
      - /actuator/info
      - /shop
