spring:
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: marche-conclu-kafka:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.igdevx.notification_service.events.NotificationEvent

notification:
  topic: notifications
