eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    url: jdbc:postgresql://db:5432/shop_service
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/dev-local
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 10s
    socket-timeout: 30s

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: product-images
  region: us-east-1
